
export DISPLAY=:99

export LANG=ja_JP.UTF-8
HISTFILE=$HOME/.zsh-history           # 履歴をファイルに保存する
HISTSIZE=1000                         # メモリ内の履歴の数
SAVEHIST=1000                         # 保存される履歴の数
setopt extended_history               # 履歴ファイルに時刻を記録

# rvm
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

#libxml2
LDFLAGS="$LDFLAGS /usr/local/Cellar/libxml2/2.7.7/lib"
CPPFLAGS="$CPPFLAGS /usr/local/Cellar/libxml2/2.7.7/include"

bindkey -e


alias svn=colorsvn
alias em=/Applications/Emacs.app/Contents/MacOS/Emacs
alias vm=vim

alias tac='tail -r'
setopt nonomatch

export EDITOR=vim
export SVN_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR

source ~/.zsh/pbcopy_buffer.zsh
source ~/.zsh/zaw/zaw.zsh
source ~/.zsh/zaw_custom.zsh
#source ~/.zsh/auto-fu_init.zsh
